### ISSUE TITLE
Add annotations and provider to CSV

### ISSUE THREAD

**Issue by jharmison-redhat** [RedHatGov/gitea-operator#11]
CSV `annotations` are what populate the extra information on the embedded OperatorHub interface. See for example the following snippet:

```yaml
apiVersion: packages.operators.coreos.com/v1
kind: PackageManifest
metadata:
# labels snipped for brevity
  name: awss3-operator-registry
  namespace: openshift-marketplace
spec: {}
status:
  catalogSource: community-operators
  catalogSourceDisplayName: Community Operators
  catalogSourceNamespace: openshift-marketplace
  catalogSourcePublisher: Red Hat
  channels:
  - currentCSV: awss3operator.1.0.1
    currentCSVDesc:
      annotations:
        alm-examples: '[]'
        capabilities: Basic Install
        categories: Storage
        certified: "false"
        containerImage: quay.io/screeley44/aws-s3-provisioner:v1.0.0
        createdAt: "2019-05-02 16:12:00"
        description: Manage the full lifecycle of installing, configuring and managing
        repository: https://github.com/yard-turkey/aws-s3-provisioner
        support: Community
      apiservicedefinitions: {}
# customresourcedefinitions, description, installModes, keywords, links, maintainers, maturity, relatedImages, version snipped for brevity
      displayName: AWS S3 Operator
      provider:
        name: Community
    name: alpha
# additional embedded CSV snipped for brevity
  defaultChannel: alpha
  packageName: awss3-operator-registry
  provider:
    name: Community
```

And reference the OperatorHub pop-out drawer for that operator:
![image](https://user-images.githubusercontent.com/55772684/93658273-39863300-fa08-11ea-830d-aac0efc0717f.png)

Compared to that for the Gitea operator:
![image](https://user-images.githubusercontent.com/55772684/93658199-74d43200-fa07-11ea-8f62-a1d3e8287578.png)

I also believe that the `provider.name: Community` is what applies the obvious `Community` label on the interface, and this should be added as well. The PackageManifest `labels` appear to have been derived from the CSV annotations and other various sources.

Other PackageManifests' nested CSVs show more verbose information for the `support` annotation, sometimes with links to the GitHub new Issue page. I think a `Community` badge on the operator with a link to the new Issue page as the `Support` tag on the web UI would be obvious enough, if my hunch on `provider.name` is right, or we can otherwise identify the proper triggers for that badge.
